"""Base definitions and interfaces for the ArchChat Multi-Agent System."""
from __future__ import annotations

import logging
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field
from app.config import RAGSettings

logger = logging.getLogger(__name__)

class AgentOutput(BaseModel):
    """Unified output structure for all agents."""
    output: Any = Field(..., description="The main result generated by the agent.")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="The confidence score of the agent's work.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Diagnostic, trace, or operational details.")

class Agent:
    """Base class for all specialized agents in ArchChat."""

    def __init__(self, settings: RAGSettings, generator: Optional[Any] = None) -> None:
        self.settings = settings
        self.generator = generator

    def run(self, input_data: Any, context: Optional[Dict[str, Any]] = None) -> AgentOutput:
        """Execute the agent logic, returning an AgentOutput."""
        raise NotImplementedError
